In [1]:
import numpy as np # biblioteca numeryczna
import sympy as sp # biblioteka do obliczeń symbolicznych

# 1.1 Podstawowe numeryczne operacje na macierzach

In [23]:
# Zdefiniujmy macierz A
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [35]:
# Zdefiniujmy macierz B
B = np.array([[5, 6], [7, 8]])
B

array([[5, 6],
       [7, 8]])

In [36]:
# Informacje o macierzy
print("Rozmiar macierzy A: ", A.shape)

Rozmiar macierzy A:  (2, 2)


In [37]:
# pierwszy wiersz
print("Pierwszy wiersz macierzy A: ", A[0,:])

Pierwszy wiersz macierzy A:  [1 2]


In [38]:
# pierwsza kolumna
print("Pierwsza kolumna macierzy A:", A[:,0])

Pierwsza kolumna macierzy A: [1 3]


In [39]:
# Dodawanie macierzy
C = A + B
C

array([[ 6,  8],
       [10, 12]])

In [40]:
# Mnożenie macierzy
D = A @ B
D

array([[19, 22],
       [43, 50]])

In [41]:
# Odwrotność macierzy
E = np.linalg.inv(A)
E

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# 1.2 Operacje na macierzach w bibliotece SymPy

In [42]:
# Zdefiniujmy macierz A
A = sp.Matrix([[1, 2], [3, 4]])
A

Matrix([
[1, 2],
[3, 4]])

In [43]:
# Zdefiniujmy macierz B
B = sp.Matrix([[5, 6], [7, 8]])
B

Matrix([
[5, 6],
[7, 8]])

In [44]:
# Mnożenie macierzy
C = A * B
C

Matrix([
[19, 22],
[43, 50]])

In [45]:
# Odwrotność macierzy
D = A.inv()
D

Matrix([
[ -2,    1],
[3/2, -1/2]])